### ISSUE TITLE
double packages

### ISSUE THREAD

**Issue by spctrlth** [YunoHost-Apps/pleroma_ynh#29]
Hi,

A while ago I started building a Pleroma-package for ynh. Eventually this package got build before I felt confident enough to share mine. While kanhu decided to not maintain it anymore, I worked further on mine[2] so I could add it to the list. Now I see this package is being maintained again and I don't know what to do...

[1] https://forum.yunohost.org/t/pleroma-for-ynh/6627
[2] https://gitlab.com/Spctrl/pleroma_ynh

**Comment by yalh76** [comment]
Hi @spctrlth, 

Sorry, I haven't gone to the forum before starting to work on Pleroma.

At the beginning of January I wanted to test Pleroma. The package in the community list didn't worked so I fixed it, made a pull request and at the end @anmol26s added me as contributor.

If @anmol26s agrees, he can add you as contributor and maybe official maintainer. I'm OK with that.
And you will be able to merge your package with this one.

I'm a newbie on Yunohost / Git / Linux ^^

**Comment by spctrlth** [comment]
> I'm a newbie on Yunohost / Git / Linux ^^

Yeah, same :stuck_out_tongue_closed_eyes: 


Note that I'm *not* planning on becoming a maintainer on a github project. The reason ynh (and Pleroma) speaks to me is because of the fact that it actually tries to decentralise the web again. I'm not to happy with the current dependency that ynh has with github and definitely don't want to make it stronger, nor do I want to be a part of it (github I mean). (Yeah, I know, my package is on gitlab, not *much* better, but still.)

The point is more that I have my package and that I'm planning on maintaining it since I need it for myself, a friend and an open fedi-server we've recently started. It just feels like a waste to not share it.

I guess the question for me is more if there's anyone who actively wants to maintain this one. 
If yes, then we'll have two packages. Not per sé a problem for me, but do we put two packages in the community list? Do I just ignore it and go on on my own?
If not, I could see if a migration from this package to mine is possible and change the repo on the community list. This is something I may need help with and definitely not something I'm gonna start doing unless there's consensus. Note that this is the first time I'm doing something like this, so I may just not realise where I'm getting myself into here either :grimacing:

**Comment by yalh76** [comment]
I think that if yunohost project is centralized on Github, it's more because having all ynh packages help to maintain them and maintainer don't have to learn different webinterfaces.
For example: https://yunohost.org/#/packaging_apps_guidelines_en 
YEP 1.7 | Add the app to the YunoHost-Apps Organization goes to https://github.com/YunoHost-Apps

BTW, I agree with you about the centralization... Maybe a good hope will be ForgeFed:
https://github.com/forgefed/forgefed an activitypub git.

So is it better to merge the github pleroma_ynh to the gitlab pleroma_ynh or the opposite. I really don't know but having two packages to do the same thing is stupid.

Maybe let somone with more experience: @anmol26s decide ^^

PS: I don't know if you have seen : 
- https://github.com/YunoHost/package_linter
- https://github.com/YunoHost/package_check
to let you improve a package
![gitlab_pleroma_ynh1](https://user-images.githubusercontent.com/30271971/52516123-ca3e3f80-2c25-11e9-9733-e250be15ad2f.PNG)
![gitlab_pleroma_ynh2](https://user-images.githubusercontent.com/30271971/52516126-cf02f380-2c25-11e9-9178-08010627fc24.PNG)

**Comment by spctrlth** [comment]
Ah, thx!
I just improved for the linter (on develop branch for now). I'll look into the other one as well

**Comment by anmol26s** [comment]
We  earlier had two packages for some same app.

We can create a another branch on github eg. peroma_fed_ynh which can be a mirror of https://gitlab.com/Spctrl/pleroma_ynh and put that in yunohost community. 

But I would warn you that this would cause confusion for the end users.

I am ready to put @spctrlth to pleroma package if he is willing to work on github.

**Comment by yalh76** [comment]
@spctrlth let us know if you agree with @anmol26s proposition

**Comment by spctrlth** [comment]
Ahoy, srry, I still had to reply, but apparently it slipped my mind :/

Yeah, no, I agree with @anmol26s that having two packages will only cause confusion. I also don't want to become a maintainer on a github project. So keep it as it is seems the best option for now.

Maybe if ynh breaks their dependency from github (e.g. by hosting their own git) things can be different, but for now I'd rather keep it as it is then.

Thanks both for your time and insights!
