### ISSUE TITLE
Avatar Change

### ISSUE THREAD

**Issue by drecksky** [YunoHost-Apps/pleroma_ynh#55]
New YNH install; uploading/changing an avatar doesn't work. No errors reported in app or journalctl.

**Comment by yalh76** [comment]
I will test that and let you know

**Comment by lesamarien** [comment]
Hello

I installed Pleroma this week and have the same problem: I can not upload images or avatars or banners. I just have the error message: Error: Upload failed. Try again later...

**Comment by lesamarien** [comment]
Si cela peut t'aider : 
Je fait un : journalctl -u pleroma --since 2019-03-22
Et j'ai le erreurs suivantes : 

Mar 22 14:39:18 mon.domaine.tld mix[18942]: 14:39:18.583 request_id=2m74n1c3ans4698n40009b21 [info] Sent 200 in 287ms
Mar 22 14:39:21 mon.domaine.tld mix[18942]: 14:39:21.700 request_id=2m74n1ie80d8ugeobo006pii [info] POST /api/statusnet/media/upload
Mar 22 14:39:21 mon.domaine.tld mix[18942]: 14:39:21.770 request_id=2m74n1ie80d8ugeobo006pii [info] Converted error File.CopyError to 500 response
Mar 22 14:39:21 mon.domaine.tld mix[18942]: 14:39:21.770 request_id=2m74n1ie80d8ugeobo006pii [error] Internal server error: %File.CopyError{action: "copy", destination: "uploads/171b5f9002d411deae0ae47f2f1e2f38a1c1a879d69d249ff8a9e1ffa20ddf08.jpg", on: "
Mar 22 14:39:21 mon.domaine.tld mix[18942]: 14:39:21.772 request_id=2m74n1ie80d8ugeobo006pii [info] Sent 500 in 71ms
Mar 22 14:39:21 mon.domaine.tld mix[18942]: 14:39:21.779 [error] #PID<0.22530.4> running Pleroma.Web.Endpoint (connection #PID<0.22529.4>, stream id 1) terminated
Mar 22 14:39:21 mon.domaine.tld mix[18942]: Server: mon.domaine.tld:80 (http)
Mar 22 14:39:21 mon.domaine.tld mix[18942]: Request: POST /api/statusnet/media/upload
Mar 22 14:39:21 mon.domaine.tld mix[18942]: ** (exit) an exception was raised:
Mar 22 14:39:21 mon.domaine.tld mix[18942]:     ** (File.CopyError) could not copy from "/tmp/plug-1553/multipart-1553261961-276457982512474-2" to "uploads/171b5f9002d411deae0ae47f2f1e2f38a1c1a879d69d249ff8a9e1ffa20ddf08.jpg": no such file or directory
Mar 22 14:39:21 mon.domaine.tld mix[18942]:         (elixir) lib/file.ex:780: File.cp!/3

**Comment by lesamarien** [comment]
Le problème vient d'être résolu pour moi. Il manquait le dossier uploads dans /var/www/pleroma/pleroma et lui donner les droits pour le compte pleroma.

J'espère que ça resoudra aussi le souci de drecksky

**Comment by drecksky** [comment]
Yes, creating an uploads folder in /var/www/pleroma/pleroma and assigning permissions to it **does** solve the problem! Je vous remercie! And thank you to yalh76 for all of your good work!

**Comment by yalh76** [comment]
Thanks for your help guys, I fixed it in the testing branch
